# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # 只添加最重要的规则
    - prefer_const_constructors
    - prefer_single_quotes
    - require_trailing_commas
    - avoid_print
    - use_key_in_widget_constructors